# Default values for powerdns.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

powerdns:
  api:
    key: PowerDNSAPI
  initDomains: []


replicaCount: 1

image:
  repository: psitrax/powerdns
  # leave tag blank to use app version
  tag:
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  # annotations: {}
  # ip

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #  cpu: 100m
  #  memory: 128Mi
  # requests:
  #  cpu: 100m
  #  memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}

##
## MariaDB chart configuration
##
mariadb:
  enabled: true

  rootUser:
    password: 

  db:
    ## MariaDB username and password
    user: powerdns
    password: powerdns
    ## Database to create
    name: powerdns

  replication:
    enabled: false

  master:
    persistence:
      enabled: false

  tests:
    enabled: false
