apiVersion: v1
kind: Secret
metadata:
  name: {{ template "powerdns.fullname" . }}
  labels:
    app: {{ template "powerdns.name" . }}
type: Opaque
data:
  api-key: "{{ .Values.powerdns.api.key | b64enc }}"
  db-user: "{{ .Values.mariadb.db.user | b64enc }}"
  db-password: "{{ .Values.mariadb.db.password | b64enc}}"
  db-name: "{{ .Values.mariadb.db.name | b64enc}}"