apiVersion: v1
kind: Service
metadata:
  name: {{ template "powerdns.fullname" . }}-dns-udp
  labels:
    app: {{ template "powerdns.name" . }}
  annotations:
{{ toYaml .Values.service.annotations | indent 4 }}
spec:
  type: {{ .Values.service.type }}
  {{- if .Values.service.ip }}
  loadBalancerIP: {{ .Values.service.ip }}
  {{- end}}
  ports:
    - port: 53
      targetPort: 53
      protocol: UDP
      name: dns-udp
  selector:
    app: {{ template "powerdns.name" . }}
    release: {{ .Release.Name }}
